version: "3.9"
services:
  mongo:
    image: mongo:6.0.4
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./mongo/db/:/data/db/
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
  swagger-ui:
    image: swaggerapi/swagger-ui:v4.18.2
    container_name: swagger-ui
    restart: unless-stopped
    ports:
      - 8084:8080
    volumes:
      - ./openapi.yml:/openapi.yml:ro
    environment:
      - SWAGGER_JSON=/openapi.yml
  # deno:
  #   image: wangyucode/deno-backend
  #   container_name: deno
  #   restart: unless-stopped
  #   environment:
  #     - TZ=Asia/Shanghai
  #   depends_on:
  #     - "mongo"
  #   volumes:
  #     - ./nginx/log/:/app/nginx/log
  #     - ./log/:/app/log/
  #     - ./.prod.env:/app/.env:ro
