name: Build Deno Backend

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.3
        with:
          deno-version: v1.37.2
      - run: deno fmt --check
      - run: deno lint
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: wangyucode
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            wangyucode/deno-backend:latest
            wangyucode/deno-backend:1.3.0
      - name: Call watchtower to check image
        run: |
          curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" wycode.cn:8086/v1/update
      - name: upload api docs
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: 'wycode.cn'
          privateKey: ${{ secrets.SERVER_KEY }}
          localDir: 'api-doc'
          dryRun: false
          compress: true
          remoteDir: '/root/data/nginx/www/swagger-ui/'
